#@data/values
---
tap:
  ingress_domain: example.com
container_registry:
  hostname: harbor.example.com
  username: admin
  password:
workshop_git:
  username: user
  branch: main
tanzunet:
  username: user@example.com
  password: